<a href="https://colab.research.google.com/github/BOBcheeto/mis433/blob/main/week2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Assignment: Python Basics
We assume you are using Python 3 in this course.

## Question 1

You've learned different data types in Python. Now, let's test your knowledge.

You need to use to format strings.

Write a program using the "f-strings" (https://realpython.com/python-f-strings/) and user input function to convert temperatures from Fahrenheit to Celsius. [Formula: Celsius = (Fahrenheit – 32)*5/9]

Hint: you may need int() or float() function

An example program output:
```
Please enter the temperature in Fahrenheit: 140
140F is 60.0 in Celsius.
```

In [ ]:
# an example of f-strings and user input function
username = input('What\'s your name? ')
print(f'Welcome, {username}!')

In [ ]:
# complete your program here
f = input('Please enter the temperature in Fahrenheit: ')

print(f)

#Celsius = (Fahrenheit – 32)*5/9
c = (f - 32) * 5/9

print(f'{f}F is {c} in Celsius. ')
#print(str(f)+'F is '+str(c)+' in Celsius. ')

Now, do the oppsoite by convert temperatures from Celsius to Fahrenheit.
Another example:
```
Please enter the temperature in Celcius: 60
60C is 140.0 in Fahrenheit.
```

In [5]:
c = int(input('Please enter the temperature in Celcius: '))

print(c)

f = c/(5/9)+32


print(f)

Please enter the temperature in Celcius: 60
60
140.0


Next, let's make it a bit challenging by adding conditional statements to convert temperatures to and from Celsius, Fahrenheit. [Formula: Celsius/5 = (Fahrenheit – 32)/9]

An example program output:
```
Please enter the temperature: 60
Is this in Celsius or Fahrenheit? C
60C is 140 in Fahrenheit
```

Another example:
```
Please enter the temperature: 140
Is this Celsius or Fahrenheit? F
140F is 60 in Celsius
```

In [1]:
# complete your program here
d = float(input('Please enter the temperature: '))
m = input('Is this in Celsius or Fahrenheit? (C or F?) ')

def tempConverter(temp, type):
  temp = temp
  if type.upper() == "C":
    temp = round(temp/(5/9)+32, 2)
    return f'{temp} in Fahrenheit'
  elif type.upper() == "F":
    temp = round((temp - 32) * 5/9, 2)
    return f'{temp} in Celsius'

  return 'error'

print(tempConverter(d, m))

Please enter the temperature: 6
Is this in Celsius or Fahrenheit? (C or F?) c
42.8 in Fahrenheit


## Question 2

Have some fun with strings.

In [23]:
sentence = "Talk is cheap. Show me the code - Linus Torvalds"

In [16]:
# Find the length of this sentence.
print(len(sentence))

48


In [29]:
# Convert the whole string to lower case.
print(sentence.lower())

talk is cheap. show me the code - linus torvalds


In [35]:
# Extract a substring from the 10th character from left to the 10th character from right.
print(sentence[9: -9])

heap. Show me the code - Linus


In [15]:
# Given the sentence, output a list of words in lowercase (without punctuations).
list = []
sentence = sentence.replace('.', '').replace('-', '').replace(' ', '').lower()
for i in range(len(sentence)):
    list.append(sentence[i])

list

['t',
 'a',
 'l',
 'k',
 'i',
 's',
 'c',
 'h',
 'e',
 'a',
 'p',
 's',
 'h',
 'o',
 'w',
 'm',
 'e',
 't',
 'h',
 'e',
 'c',
 'o',
 'd',
 'e',
 'l',
 'i',
 'n',
 'u',
 's',
 't',
 'o',
 'r',
 'v',
 'a',
 'l',
 'd',
 's']

In [24]:
# Count the total number of vowels in the sentence.
vowels = ['a','e','i','o','u']
vowels = 'aeiou'
count = 0
for i, ch in enumerate(sentence):
  if ch in vowels:
    count += 1

count

13

In [18]:
# Find the positions (indexes) of all vowels in the sentence.
list = []
for i in range(len(sentence)):
  for v in vowels:
    if sentence[i] == v:
      list.append(i)

list

[1, 4, 8, 9, 13, 16, 19, 21, 23, 25, 27, 30, 33]

## Question 3

Review list comprehension if needed: https://realpython.com/list-comprehension-python/

The formula for list comprehension is: `new_list = [expression for member in iterable (if conditional)]`

You need to do the following:

In [26]:
# Use a loop to create a list of 5 cube numbers and print the list：[0, 1, 8, 27, 64]
cubes = []
for i in range(5):
  cubes.append(i**3)

print(cubes)

[0, 1, 8, 27, 64]


In [27]:
# Use list comprehension to create the same list
cubes_lc = [i**3 for i in range(5)]
print(cubes_lc)

[0, 1, 8, 27, 64]


In [28]:
# Find the postions (indexes) of all vowels in a sentence using list comprehension
sentence = "Toto, I\'ve a feeling we\'re not in Kansas anymore. - THE WIZARD OF OZ (1939)"
positions = [i for i, ch in enumerate(sentence) if ch in vowels]
print(positions)

[1, 3, 9, 11, 14, 15, 17, 22, 25, 28, 31, 35, 38, 41, 45, 47]


In [35]:
# Use a loop to create a list of first n numbers in the Fibonacci sequence
# [0, 1, 1, 2, 3, 5, 8, ...]
fibonacci = []
n = int(input('How many numbers do you want? '))

# add your code here
if n < 0:
  print('enter a positive int')
elif n == 1:
  fibonacci = [0]
elif n == 2:
  fibonacci = [0, 1]
elif n > 2:
  fibonacci = [0, 1]
  for i in range(2,n):
    fibonacci.append(fibonacci[i-1] + fibonacci[i-2])

print(fibonacci)


How many numbers do you want? 10
[0, 1, 1, 2, 3, 5, 8, 13, 21, 34]


## Question 4

This question is about Python dictionary.

|Vaccine|Efficacy|
|-----|-------|
|Pfizer|95%|
|Moderna|95%|
|AstraZeneca|72%|
|Johnson & Johnson|66%|

Source: https://www.biospace.com/article/comparing-covid-19-vaccines-pfizer-biontech-moderna-astrazeneca-oxford-j-and-j-russia-s-sputnik-v/

In [39]:
# Create a dictionary to save the data of vaccines and their efficacy. (save 95% as 0.95)
d = {'Pfizer': .95, 'Moderna': .95, 'AstraZeneca': .72, 'Johnson & Johnson': .66}

In [40]:
v = input('Which vaccine? ')
# print the efficacy of the vaccine
print(v_dict[v])

Which vaccine? Pfizer
0.95


In [41]:
# add another vaccine 'Sputnik V' with 91.4% efficacy rate to the dictionary
d['Sputnik V'] = .914

In [46]:
# add another vaccine 'Sinovac' with 50.38% efficacy rate to the dictionary
d['Sinovac'] = .5038

In [49]:
# Print vaccines with efficacy lower than 90%.
low_efficacy_vaccines = {}
for vaccine, efficacy in d.items():
    if efficacy < 0.90:
        low_efficacy_vaccines[vaccine] = efficacy

print("Vaccines with efficacy lower than 90%:")
for vaccine, efficacy in low_efficacy_vaccines.items():
    print(f"{vaccine}: {efficacy:.2%}")

Vaccines with efficacy lower than 90%:
AstraZeneca: 72.00%
Johnson & Johnson: 66.00%


In [48]:
# delete the Sinovac vaccine from the dictionary.
del d['Sinovac']

In [51]:
#Count the occurrence of each alphabet (no space ' ') in this sentence.
sentence = 'the quick brown fox jumps over the lazy dog'

# Save the result in a dictionary
ch_dict = {}
# Use a loop to iterate all characters
# add your code here
for ch in sentence:
  if ch != ' ':
    ch_dict[ch] = ch_dict.get(ch, 0) + 1

# print the dictionary
print(ch_dict)

{'t': 2, 'h': 2, 'e': 3, 'q': 1, 'u': 2, 'i': 1, 'c': 1, 'k': 1, 'b': 1, 'r': 2, 'o': 4, 'w': 1, 'n': 1, 'f': 1, 'x': 1, 'j': 1, 'm': 1, 'p': 1, 's': 1, 'v': 1, 'l': 1, 'a': 1, 'z': 1, 'y': 1, 'd': 1, 'g': 1}


## Quesion 5

Next, we will practice with Numpy arrays.  

In [52]:
import numpy as np

In [56]:
# create a 1-D array of first 20 positive even numbers (starting with 2)
np.array([i for i in range(2, 42, 2)])

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40])

In [58]:
# create a 1-D array of first 20 positive odd numbers (starting with 1)
np.array([i+1 for i in range(0, 40, 2)])

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39])

In [59]:
# create a 10x10 array in the following format:
# first row: [0,1,...,9]
# second row: [10,11,...,19]
# ...
# tenth row: [90,91,...,99]
np.arange(100).reshape(10, 10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [64]:
# Create a 10x10 array of normally distributed random values
# with mean 0 and standard deviation 1
M = np.random.normal(loc=0, scale=1, size=(10, 10))
M.shape
M

array([[-1.23769865,  1.16201891, -1.6290935 , -1.99799467,  0.16449247,
         0.17970666,  0.90853087, -0.36148523,  0.68325049, -1.08052336],
       [ 1.35429946,  0.26718213,  1.863102  ,  0.56082166, -0.54456082,
        -0.61663632,  1.05533525, -0.13697836,  0.5446896 , -0.5911715 ],
       [-0.44439439, -1.07275677,  0.54519398, -0.7148434 , -1.24865844,
        -0.33156624,  0.72481568, -0.66375668, -0.8292491 , -0.02785851],
       [-1.44296554,  0.34686912, -0.26455995,  0.60029275,  1.07457822,
        -0.37371938,  0.10344052,  0.14986192,  0.13706766,  0.87649597],
       [ 0.27549662,  2.53902588,  0.18617241, -0.01684152,  0.50271846,
         1.33221048, -0.26042062,  0.22719748,  0.9720817 ,  0.27755785],
       [ 0.51452348,  0.5162754 ,  2.77684731,  0.53104308,  0.65730801,
        -0.57805968, -0.32719949, -1.10092333,  1.65894233, -0.08852575],
       [-0.54052419, -0.50263768,  0.53901214,  0.09476258, -1.22558137,
        -2.02856773, -0.50923189, -0.27126089

In [67]:
count = np.sum(abs(M) > 1)
print(count)

32


In [171]:
# Reference: https://numpy.org/doc/stable/reference/random/generated/numpy.random.randint.html

# Input the number of rows (input an integer >= 3)
r = int(input('Row count: '))

# Input the number of columns (input another integer >= 3)
c = int(input('column count: '))

# Hint: you may want to use the function int().

# Create a r x c array of random integers between 10 (inclusive) and 20 (exclusive).
arr = np.random.randint(10, 20, size=(r, c))
print(arr)

Row count: 16
column count: 16
[[12 12 19 16 17 19 15 13 16 19 14 10 15 13 13 18]
 [18 16 10 14 19 13 12 16 19 17 11 10 10 11 11 18]
 [18 19 15 14 19 19 19 15 18 19 18 17 10 19 13 11]
 [16 10 19 11 13 11 11 19 17 14 17 14 13 13 11 18]
 [14 14 14 13 11 19 13 13 10 15 17 10 19 14 17 13]
 [10 17 16 14 19 12 16 10 13 12 11 12 11 16 18 13]
 [13 11 17 11 19 14 19 18 13 19 12 16 19 13 11 17]
 [18 13 16 13 19 15 18 11 11 16 16 15 16 10 12 16]
 [19 18 14 13 16 13 14 11 11 11 12 17 18 12 19 17]
 [16 10 10 13 11 15 15 17 17 13 11 16 14 10 11 14]
 [10 11 10 19 17 16 12 18 16 14 12 16 13 19 11 14]
 [12 13 16 10 19 15 18 19 14 11 19 15 12 13 19 12]
 [14 18 14 15 10 19 12 12 10 16 16 15 14 11 11 11]
 [16 19 11 10 19 19 10 19 19 19 17 12 19 17 16 14]
 [19 17 12 12 14 14 14 19 16 10 16 14 14 11 11 17]
 [12 11 17 13 13 16 18 13 15 13 11 17 13 11 17 15]]


In [160]:
# output the element in the first row and the third column
if (arr.shape[0] >= 1) & (arr.shape[1] >= 3): print(arr[0, 2])

16


In [165]:
# output the element in the second row and the last column
if (arr.shape[0] >= 2) & (arr.shape[1] >= 1): print(arr[1, -1])

13


In [148]:
# output the second row of the array
if arr.shape[0] >= 2: print(arr[1, :])

[15]


In [145]:
# output the second last row of the array
if arr.shape[0] >= 2: print(arr[-2, :])

[16]


In [170]:
# output the second last column of the array
if arr.shape[1] >= 2: print(arr[:, -2])

[12 13]


In [172]:
# output the upper-left 3x3 sub-array
if (arr.shape[0] >= 3) & (arr.shape[1] >= 3): print(arr[:3, :3])

[[12 12 19]
 [18 16 10]
 [18 19 15]]


In [174]:
# output the bottom-left 3x3 sub-array
if (arr.shape[0] >= 3) & (arr.shape[1] >= 3): print(arr[-3:, :3])

[[16 19 11]
 [19 17 12]
 [12 11 17]]


In [175]:
# output the upper-right 3x3 sub-array
if (arr.shape[0] >= 3) & (arr.shape[1] >= 3): print(arr[:3, -3:])

[[13 13 18]
 [11 11 18]
 [19 13 11]]


In [176]:
# output the bottom-right 3x3 sub-array
if (arr.shape[0] >= 3) & (arr.shape[1] >= 3): print(arr[-3:, -3:])

[[17 16 14]
 [11 11 17]
 [11 17 15]]


In [193]:
# Create a 1-D array from 1 to 50 (inclusive)
A = np.arange(1,51)
# Reshape A to a 5x10 array in the following format:
A = A.reshape(5, 10)
# first row: [1,...,10]
# second row: [11,...,20]
# ...
# fifth row: [41,...,50]

print(A)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50]]


In [194]:
# add a row [51,...,60] to A
A = np.vstack([A, np.arange(51, 61)])
print(A)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50]
 [51 52 53 54 55 56 57 58 59 60]]


In [197]:
# split the new A (6x10) to two 3x10 arrays A1 and A2
A = A.reshape(2, 3, 10)
print(A)

[[[ 1  2  3  4  5  6  7  8  9 10]
  [11 12 13 14 15 16 17 18 19 20]
  [21 22 23 24 25 26 27 28 29 30]]

 [[31 32 33 34 35 36 37 38 39 40]
  [41 42 43 44 45 46 47 48 49 50]
  [51 52 53 54 55 56 57 58 59 60]]]


In [198]:
# Add 10 to each element of A
A += 10
print(A)

[[[11 12 13 14 15 16 17 18 19 20]
  [21 22 23 24 25 26 27 28 29 30]
  [31 32 33 34 35 36 37 38 39 40]]

 [[41 42 43 44 45 46 47 48 49 50]
  [51 52 53 54 55 56 57 58 59 60]
  [61 62 63 64 65 66 67 68 69 70]]]


In [200]:
# Calculate the square root of each element in A
A = A**0.5
print(A)

[[[3.31662479 3.46410162 3.60555128 3.74165739 3.87298335 4.
   4.12310563 4.24264069 4.35889894 4.47213595]
  [4.58257569 4.69041576 4.79583152 4.89897949 5.         5.09901951
   5.19615242 5.29150262 5.38516481 5.47722558]
  [5.56776436 5.65685425 5.74456265 5.83095189 5.91607978 6.
   6.08276253 6.164414   6.244998   6.32455532]]

 [[6.40312424 6.4807407  6.55743852 6.63324958 6.70820393 6.78232998
   6.8556546  6.92820323 7.         7.07106781]
  [7.14142843 7.21110255 7.28010989 7.34846923 7.41619849 7.48331477
   7.54983444 7.61577311 7.68114575 7.74596669]
  [7.81024968 7.87400787 7.93725393 8.         8.06225775 8.1240384
   8.18535277 8.24621125 8.30662386 8.36660027]]]


In [201]:
# Above, we have created a 10x10 array M of normally distributed random values
# with mean 0 and standard deviation 1
M.shape

(10, 10)

In [204]:
# Print the mean, standard devietion of all numbers in M
print(f"{np.mean(M)}, {np.std(M)}")

-0.027268014016343885, 1.03225813297312


In [207]:
# Print the maximumn, 3rd quartile, median, 1st quartile, and minimum in M
print(f"{np.max(M)}, {np.quantile(M, 0.75)}, {np.median(M)}, {np.quantile(M, 0.25)}, {np.min(M)}")

3.7112121131407685, 0.5491009006765222, -0.05819213146546993, -0.6765283618716126, -2.3852687304688835
